### ISSUE TITLE
Please fix style

### ISSUE THREAD

**Issue by yauhenipakala** [imperavi/kube#6]
Hello, please fix style for `.pagination li a:hover`

use this, for example:

``` css
.pagination li a {
    border: 1px solid #fff;
}
.pagination li a:hover {
    border: 1px solid #0f0f0f;
}
```

or `outline`
